### ISSUE TITLE
Item on the Grid View does not match BindingContext on removing item

### ISSUE THREAD

**Issue by maxchu92** [NobsterTheLobster/Xamarin.Forms.GridView#18]
If i remove second or third item from DataList in ViewModel, the item in the DataList is correctly removed. While on the screen, the first item was removed, which is incorrect. Upon changing orientation or updating the item, will update the list correctly.

Tested with Xamarin.Forms ListView and it works correctly. I did not reassign or refresh the DataList or BindingContext.

```
public class TestModel : MvvmHelpers.ObservableObject {
	int _myID = 0;
	public int MyID {
		get { return _myID; }
		set { SetProperty(ref _myID, value); }
	}

	public TestModel(int id) {
		MyID = id;
	}
}

public class TestViewModel {
	public System.Collections.ObjectModel.ObservableCollection<TestModel> DataList { get; set; }
	public TestViewModel() {
		DataList = new System.Collections.ObjectModel.ObservableCollection<TestModel> {
			new TestModel(1),
			new TestModel(2),
			new TestModel(3),
			new TestModel(4)
		};
	}
}

public class TestPage : ContentPage {
	public TestPage() : base() {
		BindingContext = new TestViewModel();
		var gvImage = new GridView {
			IsGroupingEnabled = false,
			RowHeight = 130,
			MinItemWidth = 115,
			IsPullToRefreshEnabled = false,
			ItemTemplate = new DataTemplate(BuildItemTemplate)
		};
		Grid.SetRow(gvImage, 1);
		gvImage.SetBinding(ListView.ItemsSourceProperty, "DataList");
		Content = gvImage;
	}
	public FastGridCell BuildItemTemplate() {
		var trDelete = new TapGestureRecognizer {
			Command = new Command<TestModel>((TestModel selectedItem) => {
				((TestViewModel)BindingContext).DataList.Remove(selectedItem);
			})
		};
		trDelete.SetBinding(TapGestureRecognizer.CommandParameterProperty, new Binding("."));

		var lblID = new Label();
		lblID.SetBinding(Label.TextProperty, "MyID");

		return new FastGridCell {
			View = new StackLayout {
				Padding = new Thickness(5),
				Children = { lblID }
			}
		};
	}
}
```

**Comment by NobsterTheLobster** [comment]
Yes I see the problem its sort of a catch-22; based on the collection changed event the renderer is trying to forward the index(s) of the removed item(s) to the view (recycler) but it can't find the index because the item is already removed. I should have a fix today

**Comment by NobsterTheLobster** [comment]
This issue is somewhat tricky. I believe I can handle single items being removed or inserted from the ObservableCollection class using the OldStartingIndex and NewStartingIndex properties of the CollectionChangedEventArgs and its not possible to do multi-item removes or inserts with the ObservableCollection class.  However someone could write their own collection class that implements INotifyCollectionChanged then they could very well create a CollectionChangedEventArgs that is not catered for. 

EDIT:I've had a look at Xamarin's own renderer and It turns out that they don't even distinguish between the various collection changed actions. For any and all collection changed actions Xamarin forms renderer calls NofifyDataSetChanged() from the adapter which would tell the recycler to evaluate everything. So essentially a single item being removed is the same cost as the entire collection being replaced. Obviously not very efficient.

**Comment by Bohirjon** [comment]
Hi @NobsterTheLobster,so I guess currently u are working on "Fixing this issue for uwp, ios"  right, u fixed the droid version I really need droid version could u please package the last version as an alpha release.

**Comment by NobsterTheLobster** [comment]
No I'm not working on fixing for uwp and ios because there shouldn't be an issue on those platforms.

UWP uses the default renderer with only tweaks to the itemstemplate to display as a grid. If your seeing an issue with UWP then it must be a framework issue. Try updating to the latest xamarin stable.

The iOS renderer unlike the Android renderer never tried to distinguish between collection changed events; regardless of the event the UICollectionView is told to reload everything. 

EDIT: for spelling mistakes

**Comment by Bohirjon** [comment]
@NobsterTheLobster  thanks for quick answering, will u release it soon?

**Comment by NobsterTheLobster** [comment]
Oh sorry is the nuget package behind? Ok give me a minute and I'll update nuget. Although it may take another while for it to appear in nuget.

**Comment by Bohirjon** [comment]
@NobsterTheLobster Thanks.

**Comment by NobsterTheLobster** [comment]
Ok pack updated.
