### ISSUE TITLE
Rather a question than an issue

### ISSUE THREAD

**Issue by repthor** [NobsterTheLobster/Xamarin.Forms.GridView#2]
Did you built in anything to mark the selected item on the screen?

**Comment by NobsterTheLobster** [comment]
I'll look in to it. It would be a nice feature I agree. I think there may even have been some selection visuals in the original source project that wasn't working for me. https://github.com/twintechs/TwinTechsFormsLib. In my attempts to get things laying out correctly I removed a lot of code.

On UWP there is a selected visual state since it uses the default renderer.

**Comment by repthor** [comment]
Thank You very much!

**Comment by NobsterTheLobster** [comment]
Added really basic selected item visual for android. Haven't looked at ios yet.

I think I need to rethink the whole selected item stuff and add support for multiple selection.

But if your interested in checking it out then have a look at the changed repo. You need to add a drawable to your android project Resource/Drawable/statelist_item_background.xml (if you do a find in the android renderer you'll be able to change this name to anything you want.)

In the drawable define a color for activated state (and a default state as well.)

In the sample project the activated color refers back to a color defined in the styles.xml but this is kind of messy I think.

**Comment by NobsterTheLobster** [comment]
Added support for selection visual state for ios.
