### ISSUE TITLE
DateTemplate Selector Support?

### ISSUE THREAD

**Issue by 99hats** [NobsterTheLobster/Xamarin.Forms.GridView#5]
Hi there,

Nice library. Runs very smooth. Does it support DataTemplate selector? I tried a couple of variations on that to make it work but was unsuccessful.

Best,

Kevin

**Comment by NobsterTheLobster** [comment]
I've had a look at adding datatemplate selector support to the android renderer (haven't looked at ios yet) but unfortunately it looks like it will be really tricky (maybe impossible) due to the nature of underlying recyclerview control.

A datatemplate selector typically works on the item context of the cell i.e. a different data template is chosen based on the bound item type or a property of the bound item.  However with the recycler view there is no item context at the point the template/cell is being generated (OnCreateViewHolder.) The recyclerview just knows it needs to create a cell but it doesn't know what is bound to this cell at this point. The item context is applied later (OnBindViewHolder) and the same cell may get applied a different item context over its lifetime i.e. the cell is recycled. 

I think I would have to add some code (similar to below) to the OnBindViewHolder method and try to re-generate the cell at this point but I'm not sure this is achievable or if its good practice. 

I'll keep looking at but I can't promise anything. 

var selector = Element.ItemTemplate as DataTemplateSelector;
            if (selector != null)
            {
               itemTemplate=  selector.SelectTemplate(item, _listView);
            }

**Comment by 99hats** [comment]
Ah, thanks for looking! I might need to look at my project differently.

**Comment by 99hats** [comment]
Do you think a dynamic ViewCell would work? I suppose it would need to subclass FastCell? Unfortunately, I know very little about how the renderers on each platform work.

**Comment by NobsterTheLobster** [comment]
I'm not sure I follow you about creating a dynamic view cell by subclassing the FastCell. First off do you mean FastGridCell or are you referring to the FastCell in the TwinTech source.

If your simply talking about using data triggers within your view cell then that should work fine I think but then you won't need to do anything extra in terms of the FastGridCell/FastCell.

Just to explain about the whole fastgridcell class which maybe you already fully understand but I can totally understand if you don't because the examples in the repo don't make its purpose clear at all.. 

The FastGridCell its a carry over from the TwinTech source (which you might want to check out if you haven't already, the url is in the readme.) The fastgridcell is all about squeezing the most performance by providing callbacks to...

1.  Generate the view  in the code behind (as opposed to XAML) [InitializeCell] 
2. Update the view based on the binding context without the use of bindings! [SetupCell].  

Interestingly you can kind of see how those two methods sort of line up with the OnCreateViewHolder and OnBindViewHolder methods of the recylerview I mentioned previously. Essentially the android renderer calls InitalizeCell from within OnCreateViewHolder and SetupCell from within OnBindViewHolder. The IOS renderer does something similar. 

Apparently generating the view cell in the code behind and avoiding the use of bindings is meant to provide the most performance (although perhaps that claim predates the xamarin XAML compilation feature). Regardless I don't like either of these concepts since I'm a bit of a MVVM purist and that is why the samples in the repo don't demonstrate these techniques at all.. The samples all have empty implementations of InitalizeCell and SetupCell and use a XAML view cell and bindings instead. Also if your targeting UWP then InitializeCell and SetupCell won't even be called since on UWP the default renderer is used. 

I'm not the best at explaining things but hopefully some of the above makes some kind of sense and maybe also explains why I don't follow about subclassing the FastGridCell to create a dynamic view cell.

**Comment by 99hats** [comment]
Thanks for you detailed. Reply, I feel like I'm learning a lot from this... and it's way over my head.

Mostly I'm just interested in the end game of having differently formatted view cells. 

Again, thanks so much!

**Comment by NobsterTheLobster** [comment]
Did you try it using data-triggers and/or a binding converter. Lets say you wanted to wanted a different datatemplate depending on the object type. Not sure what the performance will be like but I think it could work.

EDIT: Apologies.. I thought I had written that the code below is pseudo. I know its frustrating to be given code that doesn't work. I will hopefully have time tomorrow to actually test something and if it works I'll upload to the repo.

EDIT 2: Also apologies on the delay. Jut realised your post was a week ago. Git seems to be a bit inconsistent with its notifications.

```
public class typeToBoolConverter: IValueConverter
 {
public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
                 //Return true if the type name matches the parameter.
               return value.GetType().Name == parameter.ToString();
           }
}
```

```
<DataTemplate>
<Grid>
<Grid Name="datatemplate1" IsVisible="{Binding ., Converter={StaticResource typeToBoolConverter}, ConvertParameter=dataType1}">
<Grid Name="datatemplate2" IsVisible="{Binding ., Converter={StaticResource typeToBoolConverter}, ConvertParameter=dataType2}">
<Grid Name="datatemplate3" IsVisible="{Binding ., Converter={StaticResource typeToBoolConverter}, ConvertParameter=dataType3}">
</Grid>
</DataTemplate>
```

**Comment by NobsterTheLobster** [comment]
Check out sample3 in the repo.
